version: 3.0.{build}

skip_tags: true
clone_folder: C:\Gopath\src\alex-j-butler.com\tf2-booking

environment:
  GOPATH: C:\Gopath

install:
  - go get -u github.com/kardianos/govendor
  - cd C:\Gopath\src\alex-j-butler.com\tf2-booking
  - C:\Gopath\bin\govendor sync

build_script:
  - for /f %%i in ('git describe --always --long --dirty') do set gitrevision=%%i
  - set GOOS=linux
  - set GOARCH=amd64
  - C:\Gopath\bin\govendor build -o tf2-booking-amd64 -ldflags="-X main.version=%gitrevision%"
  - set GOOS=linux
  - set GOARCH=386
  - C:\Gopath\bin\govendor build -o tf2-booking-i386 -ldflags="-X main.version=%gitrevision%"
  - set GOOS=windows
  - set GOARCH=amd64
  - C:\Gopath\bin\govendor build -o tf2-booking-win-amd64 -ldflags="-X main.version=%gitrevision%"
  - set GOOS=windows
  - set GOARCH=386
  - C:\Gopath\bin\govendor build -o tf2-booking-win-i386 -ldflags="-X main.version=%gitrevision%"

artifacts:
  - path: tf2-booking-amd64
    name: amd64
  - path: tf2-booking-i386
    name: i386
  - path: tf2-booking-win-amd64
    name: win-amd64
  - path: tf2-booking-win-i386
    name: win-i386

deploy:
  - provider: GitHub
    release: tf2-booking-v$(appveyor_build_version)
    description: 'TF2 Booking Release'
    auth_token:
      secure: l1dGkFTQjFWX4tUrpGOkgDtXyk/+XBVkpafkQB5aA8f8gKPtGgQJN5PxOvntW4Ox
    artifact: amd64, i386, win-amd64, win-i386
    on:
      branch: master
      appveyor_repo_tag: true
